version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: quarterly
  open-pull-requests-limit: 2
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: quarterly
  open-pull-requests-limit: 2
